### ISSUE TITLE
WIP updates

### ISSUE THREAD

**Issue by keyboard-magpie** [pasyn/nanodlp-ld001-config#1]
Did you ever get anywhere with the last section of this? The nanodlp machine settings that are marked as WIP?

Many many thanks in advance...

**Comment by pasyn** [comment]
Yes. It prints but is not very tuned in yet. I can share what I currently have. I will try to upload later today.

**Comment by pasyn** [comment]
@keyboard-magpie I have added a json containing the machine settings that can be imported directly to nanoDLP

**Comment by keyboard-magpie** [comment]
Many many thanks! Sorry to drag up an old project. Much appreciated.
